# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"query_box": "00_core.ipynb",
         "query_all_recordings": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://johnowhitaker.github.io/birdio/"

git_url = "https://github.com/johnowhitaker/birdio/tree/master/"

def custom_doc_links(name): return None
