# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['query_box', 'query_all_recordings']

# Cell
import requests
import pandas as pd

# Get the first page of results for a query on a given bounding box
def query_box(LAT_MIN = -180, LAT_MAX = 180, LON_MIN = -180, LON_MAX = 180):
    response = requests.get(f'https://www.xeno-canto.org/api/2/recordings?query=box:{LAT_MIN},{LON_MIN},{LAT_MAX},{LON_MAX}')
    return response.json()

# Download a complete set of all recordings on Xeno Canto - Takes Ages, run once
def query_all_recordings(LAT_MIN = -180, LAT_MAX = 180, LON_MIN = -180, LON_MAX = 180):
    qb = query_box()
    recs = []
    for page in range(1, qb['numPages']+1):
        if page%10 == 0:
            print(str(page)+'/' + str(qb['numPages']))
        r = requests.get(f'https://www.xeno-canto.org/api/2/recordings?query=box:{LAT_MIN},{LON_MIN},{LAT_MAX},{LON_MAX}&page={page}')
        recs += r.json()['recordings']
    recordings = pd.DataFrame(recs)
    return recordings